global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'ml_service'
    metrics_path: /metrics
    static_configs:
      - targets: ['api:8000']

  - job_name: 'celery'
    static_configs:
      - targets: ['celery_exporter:9540']  

 
